#!/bin/bash
# File              : git.sh
# Author            : zhangzhao <zhangzhao@ihep.ac.cn>
# Date              : 26.09.2020
# Last Modified Date: 26.09.2020
# Last Modified By  : zhangzhao <zhangzhao@ihep.ac.cn>
#!/bin/sh
cd /home/zhangzhao/dotfiles
git add .
git commit -m "$(date)"
git push
